eventdata/runners/createindex_runner.py
With this commit we first check whether an index exists before creating
it. This avoids confusion (although the previous solution worked fine).
=> Check before creating an index

eventdata/challenges/frozen.json
With this commit we force-merge the index that is used in the frozen
challenge to a single segment. We also set the refresh interval to its
default value to ensure an optimization in Elasticsearch can kick in
that disables refreshes if no searches are performed. This should
improve indexing speed a bit (we don't care about indexing speed in that
challenge as this only there to generate a decently sized corpus for the
query benchmark).
=> Force merge index for frozen benchmarks

README.md, eventdata/challenges/index-log-volume.json, eventdata/operations/indexing.json, eventdata/parameter_sources/elasticlogs_bulk_source.py, eventdata/parameter_sources/metricbeat_bulk_source.py, eventdata/parameter_sources/randomevent.py, eventdata/parameter_sources/timeutils.py, tests/parameter_sources/randomevent_test.py, tests/parameter_sources/timeutils_test.py
With this commit we add a new challenge `index-logs-fixed-daily-volume` which
allows to ingest a fixed (but parameterizable) amount of raw logs per day. Also,
the number of days can be specified.
We also extend the existing generator with new parameters to allow this and
significantly increase testing coverage in that area after simplifying some
complex but rarely needed code in the timestamp generator.
=> Add challenge to index fixed amount of daily logs

eventdata/parameter_sources/elasticlogs_bulk_source.py, eventdata/parameter_sources/randomevent.py, tests/parameter_sources/randomevent_test.py
With this commit we implement the property `pecent_completed` on the
Elasticlogs bulk source to provide an informational progress indication
for the challenge `index-logs-fixed-daily-volume`. Because we cannot
specify a total number of iterations or a specific time-period we need
to rely on feedback from the generator when all data has been ingested
and thus we also need to rely on the generator to indicate progress.
=> Add progress indication for daily logging volume

eventdata/parameter_sources/elasticlogs_bulk_source.py, eventdata/parameter_sources/elasticlogs_kibana_source.py
With this commit we change the existing parameter sources to conform to
a new API for parameter sources in Rally. We also keep the old methods
for backwards compatibility with older releases of Rally.
Relates elastic/rally#763
=> Adjust to new parameter source API

eventdata/challenges/bulk-update.json
With this commit we use the correct property `index` in the
`bulk-update` challenge instead of the outdated property name
`index_name`. This is a leftover from #36.
`index_name` was getting ignored up until #36 because there was an 
[indices section](https://github.com/elastic/rally-eventdata-track/blob/e39208732d76a3918dbb4926d7e3f6d77eee7941/eventdata/track.json#L8-L13) having a default index (coincidentally with the same name as specified in the challenge).
With #36 `indices` got removed and became a [template](https://github.com/elastic/rally-eventdata-track/pull/36/files#diff-690d3782ebf9f9cca6b678ed111ded38R9)
causing this challenge to fail warning about the unknown property `index_name`.
=> Use correct property for index in update challenge

eventdata/parameter_sources/elasticlogs_bulk_source.py, tests/parameter_sources/elasticlogs_bulk_source_test.py
With this commit we correct the bulk size to *not* take the
action-and-metadata line into account for the bulk size calculation.
This problem has been introduced in
863d532898db476ba67e336039b4d53b5899e4d8.
=> Correct bulk size in bulk param source

smoke-test.sh
With this commit we add a smoke test script that allows to run a
benchmark in test mode against (almost) all challenges in this track. A
few challenges have been excluded intentionally because they rely on
other challenges being run first. While it would be possible to make
this work with workarounds we should wait for a proper solution with
elastic/rally#697
=> Add smoke test script

eventdata/challenges/bulk-update.json
With this commit we use the proper index template for the bulk-update
challenge. Previously neither the index template nor the custom index
settings have been applied, resulting in a default index being created
unintentionally. This issue has been discovered by the smoke test script
that we have added in #47.
=> Use index template for update challenge

README.md, eventdata/parameter_sources/elasticlogs_kibana_source.py, tests/parameter_sources/__init__.py, tests/parameter_sources/elasticlogs_bulk_source_test.py, tests/parameter_sources/elasticlogs_kibana_source_test.py
With this commit we remove some dead code from the Kibana parameter source. We
also turn `dashboard` into a mandatory parameter and add tests.
=> Cleanup Kibana Parameter Source

eventdata/parameter_sources/elasticlogs_kibana_source.py, tests/parameter_sources/elasticlogs_kibana_source_test.py, tests/parameter_sources/resources/expected-content_issues.json, tests/parameter_sources/resources/expected-discover.json, tests/parameter_sources/resources/expected-traffic.json
With this commit we switch from the deprecated `interval` aggregation to
the `fixed_interval` aggregation. We also improve the documentation of
the function that determines the interval based on the queried date
range and add more tests.
Closes #48
=> Use fixed_interval instead of interval for Kibana

eventdata/parameter_sources/elasticlogs_kibana_source.py, eventdata/runners/deleteindex_runner.py, eventdata/runners/indicesstats_runner.py, tests/parameter_sources/elasticlogs_kibana_source_test.py
With this commit we turn `index_pattern` into a mandatory parameter in
all places where it was still optional. This avoids accidental mistakes
and ensures that the intended index pattern is used.
=> Make index_pattern mandatory

README.md, eventdata/track.json
With this commit we don't only make the query index prefix overridable
but also the actual index pattern (with the track parameter
`query_index_pattern`.
=> Make query index pattern overridable

eventdata/challenges/bulk-update.json, eventdata/challenges/document_id_benchmark.json, eventdata/challenges/frozen.json, eventdata/challenges/large-shard-sizing.json, eventdata/challenges/shard-size-on-disk.json, eventdata/challenges/shard-sizing.json
This track defines an index template that defines common settings. When
bulk-indexing, indices will be automatically created based on this index
template. Therefore, explicit invocation of the create index API are
obsolete (unless they contain additional instructions such as creating
an alias).
With this commit we remove all these tasks and also related tasks (e.g.
it is not necessary to check for cluster health based on a specific
index if that index is not present yet).
=> Remove obsolete create-index tasks

eventdata/challenges/daily-log-volume-index-and-query.json, eventdata/runners/kibana_runner.py, smoke-test.sh
With this commit we first fix the index pattern so queries can actually
match data. We also change the queries so we don't run any redundant
ones and modify them to retrieve more data. Finally, we modify the
Kibana runner so it stores some metadata about the query results (number
of total hits and the maximum value of `took` across all msearch
responses).
=> Query more data for daily indices

eventdata/challenges/daily-log-volume-index-and-query.json
with this commit we lower the time window for dashboard queries from 50%
to 25% and also lower their target throughput to better match real world
use cases.
=> Lower windows for queries

eventdata/operations/querying.json
With this commit we change the dashboard to "discover" for the operation
named `current-kibana-discover_30m`. The name suggests that we intend to
use the discover functionality here but previously it has used the
traffic dashboard instead.
=> Use discover query in discover operation

eventdata/parameter_sources/elasticlogs_bulk_source.py, eventdata/parameter_sources/randomevent.py, eventdata/parameter_sources/timeutils.py, tests/parameter_sources/elasticlogs_bulk_source_test.py, tests/parameter_sources/randomevent_test.py, tests/parameter_sources/timeutils_test.py
With this commit we reduce usage of two time-consuming methods on the hot code
path: generating random numbers and determining the current timestamp. This also
changes behavior slightly:
* The `hostname` field will vary host names from 1 - 3 in a regular pattern
instead of randomly (however, as the host name is e.g. `web-EU-1.elastic.co` and
only the number changes non-randomly we deem this change ok)
* The `offset` will change be more realistic now: Before it changed randomly and
now the offset increases by the average event size up to a certain maximum.
* The current `@timestamp` will be retrieved only once per bulk. For documents
within a bulk we'll advance the microsecond portion by `1 / bulk size`
microseconds.
We've measured the performance impact of this change by stubbing out …
=> Avoid more time-consuming calls

eventdata/challenges/daily-log-volume-index-and-query.json
With this commit we expose two additional meta-data fields (`dashboard`
and `window_length`) for the `index-and-query-logs-fixed-daily-volume`
challenge. Meta-data are also propagated to Rally's results index and
can be thus used for creating more useful charts.
=> Expose additional meta-data for queries

README.md, eventdata/challenges/daily-log-volume-index.json
With this commit we expose a new track parameter `starting_point` for
the challenge `index-logs-fixed-daily-volume`. It has previously assumed
a certain date but for consistency with
`index-and-query-logs-fixed-daily-volume` we now expose a track
parameter for this date.
=> Expose starting_point for daily indexing

eventdata/runners/kibana_runner.py, tests/runners/__init__.py, tests/runners/kibana_runner_test.py
With this commit we use the top-level value for `took` across all
msearch responses if it is present. We still implement fallback logic to
use the maximum value of `took` across all responses as an
approximation. Additionally, we also introduce tests for typical cases.
=> Use top-level took value for meta-data

eventdata/runners/deleteindex_runner.py, eventdata/runners/nodestorage_runner.py
With this commit we adapt the response handling in async runners by
properly converting them from raw bytes to strings.
Relates elastic/rally#944
=> Adapt response handling in async runners

eventdata/parameter_sources/elasticlogs_bulk_source.py, eventdata/parameter_sources/elasticlogs_kibana_source.py
With this commit we remove the outdated #size() method from all
parameter sources.
Closes #43
=> Remove size() method from parameter sources

README.md, eventdata/challenges/daily-log-volume-index-and-query.json
The index-and-query-logs-fixed-daily-volume has been extended
to also be able to specify number of search clients, useful
for verifying workload patterns exhausing the available threads
in the search thread pool.
=> Add search_clients parameter

eventdata/elasticlogs-index-template.json
With this commit we define the index prefix also in the index template
definition and not only in the track. Because the index template
definition is stored in a separate file, template variables defined in
the track are not effective and thus need to be defined separately.
=> Ensure index prefix is used in index template

eventdata/parameter_sources/elasticlogs_bulk_source.py, tests/parameter_sources/elasticlogs_bulk_source_test.py
With this commit we add a new parameter `unit` to this track's bulk
parameter source. This parameter is mandatory for bulk parameter sources
since elastic/rally#1100.
Relates elastic/rally#1100
=> Make track Rally 2.0.3-compatible

README.md, eventdata/challenges/query-searchable-snapshot.json, eventdata/runners/mount_searchable_snapshot_runner.py, eventdata/track.py, tests/runners/mount_searchable_snapshot_runner_test.py
With this commit we add a new challenge `query-searchable-snapshot`
which can be used to evaluate the performance of searchable snapshots.
The challenge assumes that an appropriate snapshot has already been
created.
=> Add query-searchable-snapshot challenge

eventdata/runners/mount_searchable_snapshot_runner.py, tests/runners/mount_searchable_snapshot_runner_test.py
With this commit we allow to mount searchable snapshots with the 7.x and
the 8.x response format as the get snapshot API has changed in between
versions.
Relates #93
=> Make searchable snapshots more compatible

eventdata/challenges/query-searchable-snapshot.json
With this commit we retry the cluster health check after mounting a
searchable snapshot to ensure we continue only when the cluster is
ready. We also address a couple of formatting issues.
=> Wait until cluster status is green after mount

eventdata/challenges/frozen.json
With this commit we retry the cluster health check until the cluster is
green. Without this change the cluster health check might time out
before the desired status has been reached and the benchmark continues
earlier than intended.
Relates #95
=> Wait until cluster health is green

eventdata/runners/deleteindex_runner.py, eventdata/runners/fieldstats_runner.py, eventdata/runners/indicesstats_runner.py, eventdata/runners/kibana_runner.py, eventdata/runners/nodestorage_runner.py, eventdata/runners/rollover_runner.py, eventdata/track.py, tests/runners/kibana_runner_test.py
With this commit we remove all runners that use the blocking
Elasticsearch client API methods. This means that this track requires at
least Rally 2.0.0 (released on May 7, 2020).
Closes #81
=> Remove async backwards-compatibility layer

Makefile, README.md, eventdata/challenges/daily-log-index-fixed-throughput-and-query.json, eventdata/challenges/daily-log-volume-index-and-query.json, eventdata/challenges/daily-log-volume-index.json, smoke-test.sh
Add a challenge that runs three parallel queries while running in
parallel an indexing task with fixed throughput (supplied via a track
param).
Also fix track parameter bugs in README and allow specifying the
index_prefix in the challenges `index-and-query-logs-fixed-daily-volume`
and `index-logs-fixed-daily-volume`.
=> Commit fixed indexing load and parallel query challenge

README.md, smoke-test.sh
With this commit we always specify an explicit subcommand as Rally will
soon require it for all invocations.
Relates elastic/rally#1155
=> Invoke Rally with explicit subcommand

eventdata/runners/mount_searchable_snapshot_runner.py, tests/runners/mount_searchable_snapshot_runner_test.py
Allow customization of the mount searchable snapshots runner via
query params.
=> Support parameters for mount snapshots

eventdata/challenges/frozen.json, eventdata/parameter_sources/elasticlogs_kibana_source.py, eventdata/runners/kibana_runner.py, tests/parameter_sources/elasticlogs_kibana_source_test.py, tests/parameter_sources/resources/expected-content_issues.json, tests/parameter_sources/resources/expected-discover-random-window-length.json, tests/parameter_sources/resources/expected-discover.json, tests/parameter_sources/resources/expected-traffic.json, tests/runners/kibana_runner_test.py
Adds support for the `max_concurrent_shard_requests` request parameter on searches, which is useful to set to higher values in the context of the searchable snapshots frozen tier.
Also slightly refactors the Kibana runner so that request options become a proper thing, making it easier to add more.
=> Add max_concurrent_shard_requests parameter to Kibana runner

eventdata/runners/mount_searchable_snapshot_runner.py, tests/runners/mount_searchable_snapshot_runner_test.py
Sometimes we only want to mount a subset of the indices in a snapshot. This generalizes the MountSearchableSnapshotRunner to allow specifying a index pattern so that only a subset of the indices in a snapshot are mounted.
=> Allow searchable snapshot runner to mount only subset of indices

eventdata/runners/nodestorage_runner.py
Make the runner work for clusters with data_hot, frozen node roles.
Closes: https://github.com/elastic/rally-eventdata-track/issues/108
=> Add check for `hot` and `frozen` for nodestorage runner

eventdata/runners/nodestorage_runner.py
Similar to https://github.com/elastic/rally-tracks/pull/380, this ensures the runner is BWC with the 7.x ES client.
You can test this with:
```
esrally race --track-path="/my/path/to/eventdata" --kill-running-processes --test-mode --track-params="number_of_replicas: 0" --test-mode
```
=> Make 'nodestorage' runner BWC

eventdata/runners/deleteindex_runner.py
Same as https://github.com/elastic/rally-eventdata-track/pull/115, was missed in the last PR.
=> Make 'deleteindex_runner' backwards compatible 
